[graph]
all-features = true

[advisories]
ignore = []
version = 2

[licenses]
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "ISC",
  "MIT",
  "Unicode-3.0",
]
confidence-threshold = 0.8
version = 2

[bans]
highlight = "all"
multiple-versions = "deny"
skip = [
  { name = "getrandom", version = "=0.2.17" },
  { name = "windows-sys", version = "=0.52.0" },
  { name = "windows-sys", version = "=0.60.2" },
  { name = "windows-targets", version = "=0.52.6" },
  { name = "windows_aarch64_gnullvm", version = "=0.52.6" },
  { name = "windows_aarch64_msvc", version = "=0.52.6" },
  { name = "windows_i686_gnu", version = "=0.52.6" },
  { name = "windows_i686_gnullvm", version = "=0.52.6" },
  { name = "windows_i686_msvc", version = "=0.52.6" },
  { name = "windows_x86_64_gnu", version = "=0.52.6" },
  { name = "windows_x86_64_gnullvm", version = "=0.52.6" },
  { name = "windows_x86_64_msvc", version = "=0.52.6" },
]
wildcards = "deny"

[sources]
allow-git = []
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
unknown-git = "deny"
unknown-registry = "deny"
