[graph]
all-features = true

[advisories]
ignore = []
version = 2

[licenses]
allow = [
  "Apache-2.0",
  "MIT",
]
confidence-threshold = 0.8
version = 2

[bans]
highlight = "all"
multiple-versions = "deny"
wildcards = "deny"

[sources]
allow-git = []
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
unknown-git = "deny"
unknown-registry = "deny"
