[default]
extend-ignore-identifiers-re = [
  "Madobe",
  "madobectl",
]

[default.extend-words]
CLL = "CLL"
cmo = "cmo"
EIS = "EIS"
FALL = "FALL"
MaxCLL = "MaxCLL"
MaxFALL = "MaxFALL"

[files]
extend-exclude = [
  ".qd/qd.db",
  ".qd/qd.db-*",
  "lcov.info",
  "target",
]
