disabled_rules:
  - trailing_comma
opt_in_rules:
  - empty_count
  - explicit_init
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - sorted_imports
line_length:
  warning: 120
  error: 140
type_name:
  min_length: 3
identifier_name:
  min_length: 2
included:
  - Sources
  - Tests
