//! Product QUIC AV1 sample smoke harness.
//!
//! This module sends the checked-in IVF sample as opaque bytes over Quinn and
//! validates byte count plus SHA-256 on receive. It is product QUIC transport
//! evidence only; it does not decode, render, present, or measure latency.

mod artifacts;
mod cli;
mod error;

use std::fs;
use std::net::{IpAddr, Ipv4Addr, SocketAddr, ToSocketAddrs};
use std::path::PathBuf;
use std::sync::Arc;

use madobe_protocol::PayloadHashAlgorithm;
use quinn::{ClientConfig, Endpoint, ServerConfig};
use rcgen::CertifiedKey;
use rustls::RootCertStore;
use rustls::pki_types::CertificateDer;
use tokio::runtime::{Builder, Runtime};

use crate::sha256;
use crate::video_smoke::{CHECKED_IN_AV1_SAMPLE, CHECKED_IN_AV1_SHA256, SmokeSample};

pub use artifacts::ProductQuicArtifactSet;
pub use cli::run_cli;
pub use error::{ProductQuicError, ProductQuicErrorKind};

/// Stable node id recorded in product QUIC smoke artifacts.
pub const NODE_ID: &str = "m4-product-quic-cross-device-smoke";

const MAX_MESSAGE_BYTES: usize = 1024 * 1024;
const WIRE_MAGIC: &str = "MADOBE_PRODUCT_QUIC_SMOKE_V1";

/// Options for a product QUIC sample sender run.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProductQuicSendOptions {
    /// Remote peer address to dial.
    pub addr: String,
    /// TLS server name expected in the receiver certificate SANs.
    pub server_name: String,
    /// DER certificate generated by the receiver and trusted by this sender.
    pub server_cert_der: PathBuf,
    /// Checked-in sample path to send.
    pub sample_path: PathBuf,
    /// Optional artifact output directory.
    pub artifact_dir: Option<PathBuf>,
}

/// Options for a product QUIC sample receiver run.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProductQuicReceiveOptions {
    /// Local UDP address to bind.
    pub bind: String,
    /// TLS SANs to put in the generated self-signed certificate.
    pub cert_subject_alt_names: Vec<String>,
    /// Optional artifact output directory.
    pub artifact_dir: Option<PathBuf>,
}

/// Summary returned by a product QUIC sender run.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProductQuicSendSummary {
    /// Remote peer address used by the sender.
    pub remote_addr: SocketAddr,
    /// TLS server name used for certificate validation.
    pub server_name: String,
    /// Number of payload bytes sent.
    pub payload_bytes: usize,
    /// SHA-256 computed over sent payload bytes.
    pub payload_sha256: String,
    /// Receiver acknowledgement text.
    pub ack: String,
}

/// Validation summary returned by a product QUIC receiver run.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProductQuicReceiveSummary {
    /// Local UDP address used by the receiver.
    pub local_addr: SocketAddr,
    /// Sender peer address accepted by the receiver.
    pub peer_addr: SocketAddr,
    /// Number of payload bytes received.
    pub payload_bytes: usize,
    /// SHA-256 computed over received payload bytes.
    pub payload_sha256: String,
    /// Whether all receiver validation checks passed.
    pub passed: bool,
}

/// Sends the checked-in AV1 sample over product QUIC.
///
/// # Errors
///
/// Returns an error when the sample cannot be loaded, TLS trust cannot be
/// configured, the peer cannot be reached, QUIC send/receive fails, or
/// artifact files cannot be written.
pub fn send_checked_av1_sample(
    options: &ProductQuicSendOptions,
) -> Result<ProductQuicSendSummary, ProductQuicError> {
    runtime()?.block_on(send_checked_av1_sample_async(options))
}

/// Receives and validates one checked-in AV1 sample over product QUIC.
///
/// # Errors
///
/// Returns an error when binding, certificate generation, receiving,
/// validating, or artifact writing fails.
pub fn receive_checked_av1_sample(
    options: &ProductQuicReceiveOptions,
) -> Result<ProductQuicReceiveSummary, ProductQuicError> {
    runtime()?.block_on(receive_checked_av1_sample_async(options))
}

async fn send_checked_av1_sample_async(
    options: &ProductQuicSendOptions,
) -> Result<ProductQuicSendSummary, ProductQuicError> {
    let remote_addr = resolve_one(&options.addr)?;
    let artifacts = ProductQuicArtifactSet::new(options.artifact_dir.as_deref());
    let sample = SmokeSample::load(&options.sample_path)
        .map_err(|error| ProductQuicError::sample(&error))?;
    validate_loaded_sample(&sample)?;
    let payload_sha256 = sha256::digest_hex(&sample.payload);
    let message = encode_message(&sample, &payload_sha256);
    let certificate = fs::read(&options.server_cert_der)
        .map_err(|error| ProductQuicError::io("read server certificate", &error))?;

    let mut endpoint = Endpoint::client(SocketAddr::new(IpAddr::V4(Ipv4Addr::UNSPECIFIED), 0))
        .map_err(|error| ProductQuicError::quic("create client endpoint", error))?;
    endpoint.set_default_client_config(client_config_trusting(certificate)?);
    let connection = endpoint
        .connect(remote_addr, &options.server_name)
        .map_err(|error| ProductQuicError::quic("connect", error))?
        .await
        .map_err(|error| ProductQuicError::quic("client handshake", error))?;
    let (mut send, mut recv) = connection
        .open_bi()
        .await
        .map_err(|error| ProductQuicError::quic("open bidi stream", error))?;
    send.write_all(&message)
        .await
        .map_err(|error| ProductQuicError::quic("write sample", error))?;
    send.finish()
        .map_err(|error| ProductQuicError::quic("finish stream", error))?;
    let ack = recv
        .read_to_end(MAX_MESSAGE_BYTES)
        .await
        .map_err(|error| ProductQuicError::quic("read ack", error))?;
    let ack = String::from_utf8(ack)
        .map_err(|error| ProductQuicError::validation(format!("ack was not utf-8: {error}")))?;
    validate_ack(&ack, &payload_sha256)?;
    connection.close(0_u32.into(), b"done");
    endpoint.wait_idle().await;

    let summary = ProductQuicSendSummary {
        remote_addr,
        server_name: options.server_name.clone(),
        payload_bytes: sample.payload.len(),
        payload_sha256,
        ack,
    };
    artifacts.write_sender(&summary)?;

    Ok(summary)
}

async fn receive_checked_av1_sample_async(
    options: &ProductQuicReceiveOptions,
) -> Result<ProductQuicReceiveSummary, ProductQuicError> {
    let bind_addr = resolve_one(&options.bind)?;
    let artifacts = ProductQuicArtifactSet::new(options.artifact_dir.as_deref());
    let (server_config, cert_der) =
        self_signed_server_config(options.cert_subject_alt_names.clone())?;
    let endpoint = Endpoint::server(server_config, bind_addr)
        .map_err(|error| ProductQuicError::quic("create server endpoint", error))?;
    let local_addr = endpoint
        .local_addr()
        .map_err(|error| ProductQuicError::quic("read server local address", error))?;
    artifacts.write_receiver_listening(local_addr, &cert_der)?;

    let incoming = endpoint
        .accept()
        .await
        .ok_or_else(|| ProductQuicError::validation("server endpoint stopped accepting"))?;
    let connection = incoming
        .await
        .map_err(|error| ProductQuicError::quic("server handshake", error))?;
    let peer_addr = connection.remote_address();
    let (mut send, mut recv) = connection
        .accept_bi()
        .await
        .map_err(|error| ProductQuicError::quic("accept bidi stream", error))?;
    let message = recv
        .read_to_end(MAX_MESSAGE_BYTES)
        .await
        .map_err(|error| ProductQuicError::quic("read sample", error))?;
    let sample = decode_message(&message)?;
    validate_loaded_sample(&sample)?;
    let payload_sha256 = sha256::digest_hex(&sample.payload);
    validate_received_sample(&sample, &payload_sha256)?;
    let ack = format!("ok sha256={payload_sha256}\n");
    send.write_all(ack.as_bytes())
        .await
        .map_err(|error| ProductQuicError::quic("write ack", error))?;
    send.finish()
        .map_err(|error| ProductQuicError::quic("finish ack", error))?;
    let stopped = send
        .stopped()
        .await
        .map_err(|error| ProductQuicError::quic("wait for ack delivery", error))?;
    if let Some(error_code) = stopped {
        return Err(ProductQuicError::validation(format!(
            "sender stopped ack stream with error code {error_code}"
        )));
    }

    let summary = ProductQuicReceiveSummary {
        local_addr,
        peer_addr,
        payload_bytes: sample.payload.len(),
        payload_sha256,
        passed: true,
    };
    artifacts.write_receiver(&summary)?;

    Ok(summary)
}

fn runtime() -> Result<Runtime, ProductQuicError> {
    Builder::new_multi_thread()
        .enable_io()
        .enable_time()
        .build()
        .map_err(|error| ProductQuicError::runtime(&error))
}

fn self_signed_server_config(
    mut subject_alt_names: Vec<String>,
) -> Result<(ServerConfig, Vec<u8>), ProductQuicError> {
    if subject_alt_names.is_empty() {
        subject_alt_names.push("localhost".to_owned());
    }
    let CertifiedKey { cert, signing_key } = rcgen::generate_simple_self_signed(subject_alt_names)
        .map_err(|error| ProductQuicError::tls("generate certificate", error))?;
    let cert_der = CertificateDer::from(cert);
    let server_config = ServerConfig::with_single_cert(vec![cert_der.clone()], signing_key.into())
        .map_err(|error| ProductQuicError::tls("build server config", error))?;

    Ok((server_config, cert_der.to_vec()))
}

fn client_config_trusting(cert_der: Vec<u8>) -> Result<ClientConfig, ProductQuicError> {
    let mut roots = RootCertStore::empty();
    roots
        .add(CertificateDer::from(cert_der))
        .map_err(|error| ProductQuicError::tls("trust server certificate", error))?;
    ClientConfig::with_root_certificates(Arc::new(roots))
        .map_err(|error| ProductQuicError::tls("build client config", error))
}

fn encode_message(sample: &SmokeSample, payload_sha256: &str) -> Vec<u8> {
    let header = format!(
        concat!(
            "{wire_magic}\n",
            "frame_id={frame_id}\n",
            "codec={codec}\n",
            "width={width}\n",
            "height={height}\n",
            "payload_bytes={payload_bytes}\n",
            "sha256={sha256}\n",
            "\n"
        ),
        wire_magic = WIRE_MAGIC,
        frame_id = sample.metadata.frame_id,
        codec = sample.metadata.codec.wire_name(),
        width = sample.metadata.width,
        height = sample.metadata.height,
        payload_bytes = sample.payload.len(),
        sha256 = payload_sha256,
    );
    let mut message = header.into_bytes();
    message.extend_from_slice(&sample.payload);

    message
}

fn decode_message(message: &[u8]) -> Result<SmokeSample, ProductQuicError> {
    let separator = message
        .windows(2)
        .position(|window| window == b"\n\n")
        .ok_or_else(|| ProductQuicError::wire("message missing header terminator"))?;
    let header = std::str::from_utf8(&message[..separator])
        .map_err(|error| ProductQuicError::wire(format!("header was not utf-8: {error}")))?;
    let payload = message[separator + 2..].to_vec();
    let expected_bytes = header_value(header, "payload_bytes")?
        .parse::<usize>()
        .map_err(|error| ProductQuicError::wire(format!("invalid payload_bytes: {error}")))?;
    if expected_bytes != payload.len() {
        return Err(ProductQuicError::validation(format!(
            "header declared {expected_bytes} bytes but received {}",
            payload.len()
        )));
    }
    let expected_sha = header_value(header, "sha256")?;
    let actual_sha = sha256::digest_hex(&payload);
    if expected_sha != actual_sha {
        return Err(ProductQuicError::validation(format!(
            "payload sha256 {actual_sha} did not match header {expected_sha}"
        )));
    }
    if actual_sha != CHECKED_IN_AV1_SHA256 {
        return Err(ProductQuicError::validation(format!(
            "payload sha256 {actual_sha} did not match checked-in sample {CHECKED_IN_AV1_SHA256}"
        )));
    }

    SmokeSample::from_checked_payload(payload, CHECKED_IN_AV1_SAMPLE)
        .map_err(|error| ProductQuicError::sample(&error))
}

fn header_value<'a>(header: &'a str, key: &str) -> Result<&'a str, ProductQuicError> {
    let mut lines = header.lines();
    match lines.next() {
        Some(WIRE_MAGIC) => {}
        _ => return Err(ProductQuicError::wire("unexpected product QUIC magic")),
    }
    let prefix = format!("{key}=");
    lines
        .find_map(|line| line.strip_prefix(&prefix))
        .ok_or_else(|| ProductQuicError::wire(format!("missing {key} header")))
}

fn validate_loaded_sample(sample: &SmokeSample) -> Result<(), ProductQuicError> {
    if sample.metadata.payload_hash.algorithm != PayloadHashAlgorithm::Sha256 {
        return Err(ProductQuicError::validation(
            "sample hash algorithm was not sha256",
        ));
    }
    validate_received_sample(sample, &sha256::digest_hex(&sample.payload))
}

fn validate_received_sample(
    sample: &SmokeSample,
    payload_sha256: &str,
) -> Result<(), ProductQuicError> {
    if sample.metadata.payload_bytes != 84 || sample.payload.len() != 84 {
        return Err(ProductQuicError::validation(
            "payload byte count was not 84",
        ));
    }
    if sample.metadata.payload_hash.value != CHECKED_IN_AV1_SHA256 {
        return Err(ProductQuicError::validation(
            "metadata hash did not match checked-in sample",
        ));
    }
    if payload_sha256 != sample.metadata.payload_hash.value {
        return Err(ProductQuicError::validation(
            "payload bytes did not match metadata sha256",
        ));
    }

    Ok(())
}

fn validate_ack(ack: &str, payload_sha256: &str) -> Result<(), ProductQuicError> {
    let expected = format!("ok sha256={payload_sha256}\n");
    if ack == expected {
        Ok(())
    } else {
        Err(ProductQuicError::validation(format!(
            "unexpected receiver ack {ack:?}"
        )))
    }
}

fn resolve_one(addr: impl ToSocketAddrs) -> Result<SocketAddr, ProductQuicError> {
    addr.to_socket_addrs()
        .map_err(|error| ProductQuicError::io("resolve address", &error))?
        .next()
        .ok_or_else(|| ProductQuicError::usage("address resolved to no socket addresses"))
}
